[header]
stamp = 1970-01-01T02:54:13
frame_id = "base_scan"

[scan]
angle_min = 0.0
angle_max = 6.28000020980835
angle_increment = 0.01749303564429283

time_increment = 0.0
scan_time = 0.0

range_min = 0.11999999731779099
range_max = 3.5

ranges = [
  1.6114528179168701, 1.614149570465088, 1.6091277599334717, 1.6019562482833862, 1.607688069343567, 1.6112537384033203, 1.5939116477966309,
  1.5776989459991455, 1.5760207176208496, 1.5905245542526245, 1.5624916553497314, 1.5839009284973145, 1.5955357551574707, 1.5759073495864868,
  1.5919493436813354, 1.577872633934021, 1.5672657489776611, 1.5927097797393799, 1.620435357093811, 1.6068406105041504, 1.6144914627075195,
  1.5935566425323486, 1.597550630569458, 1.6059566736221313, 1.6209964752197266, 1.6171342134475708, 1.6294039487838745, 1.6281065940856934,
  1.632641077041626, 1.6585396528244019, 1.6745234727859497, 1.6708437204360962, 1.6901131868362427, 1.7079133987426758, 1.711348295211792,
  1.7177411317825317, 1.7171412706375122, 1.7635116577148438, 1.7566304206848145, 0.18760856986045837, 0.19220653176307678, 0.1722981482744217,
  0.155798077583313, 0.1692844182252884, 0.13946828246116638, 0.14522592723369598, 0.12714321911334991, 0.1308833807706833, 0.13171182572841644,
  0.14561085402965546, 0.11999999731779099, 0.11999999731779099, 0.11999999731779099, 0.11999999731779099, 0.11999999731779099,
  0.3395625054836273, 0.3409692645072937, 0.3350435495376587, 0.3379051387310028, 0.34042835235595703, 0.3374619483947754, 0.3387383222579956,
  0.34215661883354187, 0.33813175559043884, 0.3593255877494812, 0.37018924951553345, 0.32942816615104675, 0.3479911684989929, 0.3594028949737549,
  0.34527748823165894, 0.34327661991119385, 0.34438130259513855, 0.3427148163318634, 0.36070483922958374, 0.34878775477409363, 0.3374060392379761,
  0.3446042835712433, 0.3640202581882477, 0.3385884463787079, 0.356292188167572, 0.3544120788574219, 0.31548964977264404, 0.3107992112636566,
  0.3254795968532562, 0.3379800319671631, 0.12609723210334778, 0.11999999731779099, 0.14151842892169952, 0.12163007259368896, 0.1364600509405136,
  0.14388127624988556, 0.15095718204975128, 0.13442476093769073, 0.13225555419921875, 0.14879709482192993, 0.14342017471790314, 0.15566399693489075,
  0.16089141368865967, 0.15427763760089874, 0.1582777351140976, 0.18049775063991547, 2.57146954536438, 2.5985524654388428, 2.609790563583374,
  2.6362102031707764, 2.6401021480560303, 2.6807169914245605, 2.6929142475128174, 2.721238613128662, 0.09711099870057822, 134.53482822881756,
  -1.0, 0.07354539015857699, 0.025011261253480972, 188.81848534223604, -5.147190821610109, 0.02559470326478562, 677.216280568883, 997.8357239788704,
  6.575515603651736, 592.2349330261754, 3.3233284950256348, 3.1175341606140137, 2.924872636795044, 2.7708511352539062, 2.6150012016296387,
  2.4993350505828857, 2.3924241065979004, 2.293210983276367, 2.202633857727051, 2.0827796459198, 2.0014331340789795, 1.9424294233322144,
  1.8782098293304443, 1.8950592279434204, 1.9205787181854248, 1.9262304306030273, 1.964401125907898, 1.9704385995864868, 1.9860793352127075,
  2.0221478939056396, -3.7979889523439905, -249.90346105696858, 8.964079370610952, -5.884819667991032, 902.7340963844741, 9.079427216485987,
  378.4236557633534, -835.4970409105172, 0.04101925824504599, 357.393492808723, 864.3092190022951, 379.8034716296025, 0.05714295512341604,
  -928.1724320569413, 257.06217161879397, -290.49897366284847, 0.011914349112089467, 3.3881325721740723, 3.2788777351379395, 3.188422918319702,
  3.0956289768218994, 3.012479543685913, 2.926370143890381, 2.864959955215454, 2.781029462814331, 2.719940423965454, 2.6614768505096436,
  2.5895252227783203, 2.5316922664642334, 2.4774951934814453, 2.419987916946411, 2.3768880367279053, 2.3374390602111816, 2.2920637130737305,
  2.2591872215270996, 2.230992078781128, 2.170464038848877, 2.145038604736328, 2.1167969703674316, 2.076291799545288, 2.0705180168151855,
  2.034424066543579, 2.001206398010254, 1.9788700342178345, 1.9525835514068604, 1.9970853328704834, -474.27907918826645, -496.806442585849,
  957.3700092227706, -9.516738325994037, 8.651749061316103, -5.097056109718616, -1.0, -1.0, 7.411335542815987, -0.4718187145634669, -1.0,
  2.9209816455841064, 2.872441291809082, 2.901685953140259, 2.893928050994873, 2.9319345951080322, 2.9362030029296875, 2.940922498703003,
  2.9528274536132812, 2.997870445251465, 3.006344795227051, 3.033287525177002, 3.064846992492676, 3.0860135555267334, 3.0928869247436523,
  3.1122498512268066, 3.153956651687622, 3.166767120361328, 3.1938672065734863, 3.2463080883026123, 3.270981788635254, 3.301595687866211,
  3.340749502182007, 3.388132333755493, 3.4224934577941895, 2.922767400741577, 2.732370138168335, 2.698220729827881, 2.701500415802002,
  2.691089153289795, 2.7423107624053955, 3.0433833599090576, 3.0654990673065186, 2.786608934402466, 2.7905876636505127, 2.7944037914276123,
  2.8055756092071533, 2.8250038623809814, 2.813041925430298, 2.7985143661499023, 2.8250627517700195, 2.822486639022827, 2.8147695064544678,
  2.8233842849731445, 2.823857545852661, 2.852905750274658, 2.8571412563323975, 2.8755524158477783, 2.8718137741088867, 2.8780906200408936,
  2.9092018604278564, 2.9067018032073975, 2.927612543106079, 2.942519187927246, 2.9709315299987793, 2.974527359008789, 3.002420663833618,
  3.037001132965088, 3.0399441719055176, 3.0791075229644775, 3.080275297164917, 3.1373229026794434, 3.1413228511810303, 3.196333885192871,
  3.19704532623291, 3.2225849628448486, 3.2680418491363525, 3.3054141998291016, 3.351541519165039, 3.389496088027954, 3.422053813934326,
  3.4819068908691406, -3.9926611841393624, -1.0, -1.0, 590.310351395053, -1.0, 0.014974757830473067, 789.9717081197209, -214.6703274527331,
  458.55066009578985, 0.021647704329776953, 201.12177755146521, 4.232687862567838, 109.38536891449819, -1.2802487656262116, -1.0,
  0.05639364957305379, -662.5391163972715, 2.617692470550537, 2.5956852436065674, 2.582712173461914, 2.5650055408477783, 2.568080186843872,
  2.5492658615112305, 2.75557541847229, 3.057356119155884, 3.478041887283325, -1.0, -797.4593214034458, 0.08321570717934788, 531.6362276384059,
  -470.0610682648851, 8.909156516058966, 934.076695970137, 3.354207754135132, 3.265766143798828, 3.206402063369751, 3.1369385719299316,
  3.0691113471984863, 3.0296545028686523, 2.968797445297241, 2.9102675914764404, 2.860109329223633, 2.8131539821624756, 2.7596328258514404,
  2.7323670387268066, 2.664025068283081, 2.646031379699707, 2.5954830646514893, 2.5629966259002686, 2.523437976837158, 2.49849009513855,
  2.4766385555267334, 2.428485631942749, 2.427677631378174, 2.385686159133911, 2.3579514026641846, 2.343353748321533, 2.3117077350616455,
  2.2918083667755127, 2.268611431121826, 2.249455690383911, 2.2353062629699707, 2.2048094272613525, 2.2023143768310547, 2.200122833251953,
  2.1450443267822266, 2.1676931381225586, 2.145580768585205, 2.1280903816223145, 2.1152379512786865, 2.097139596939087, 2.1005115509033203,
  2.055406332015991, 2.0832810401916504, 2.080253839492798, 2.0646045207977295, 2.0576798915863037, 2.047773838043213, 0.08258237724883227,
  -1.0, 588.7675045362668, -1.0, -1.0, 1.6759352684020996, 1.6551623344421387, 1.6532669067382812, 1.6593929529190063, 1.6507608890533447,
  1.6372907161712646, 1.6145457029342651, 1.613012671470642
]

intensities = []
